name: Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  pre-destroy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tofu_xc_resources
    needs: pre-destroy
    env:
      VES_P12_PASSWORD: ${{ secrets.VES_P12_PASSWORD }}
      VES_P12_CONTENT: ${{ secrets.VES_P12_CONTENT }}
      TF_VAR_ssh_pub_key: ${{ secrets.TF_VAR_ssh_pub_key }}
      TF_BACKEND_AWS_BUCKET_NAME: ${{ vars.TF_BACKEND_AWS_BUCKET_NAME }}
      TF_BACKEND_AWS_BUCKET_KEY: ${{ vars.TF_BACKEND_AWS_BUCKET_KEY }}
      TF_BACKEND_AWS_BUCKET_REGION: ${{ vars.TF_BACKEND_AWS_BUCKET_REGION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.10.7

    # Tofy init with a specific AWS S3 backend
    - name: Tofu Init
      run: |
        tofu init \
          -backend-config="bucket=$TF_BACKEND_AWS_BUCKET_NAME" \
          -backend-config="key=$TF_BACKEND_AWS_BUCKET_KEY" \
          -backend-config="region=$TF_BACKEND_AWS_BUCKET_REGION"

    # Destroy
    - name: Tofu destroy
      run: |
        tofu destroy -auto-approve
